### ISSUE TITLE
Файл .gitignore

### ISSUE THREAD

**Issue by tyndria** [CameronCobb/training-practice#2]
Вынесите, пожалуйста, файлик .gitignore в корень, он не должен лежать внутри task1 (хотя вообще может, конечно, но по заданию лучше, чтобы в корне лежал)

**Comment by CameronCobb** [comment]
Где можно глянуть зачтено / не зачтено и т.д?

**Comment by tyndria** [comment]
@CameronCobb , удалите лишний .gitignore, тогда зачтем
