### ISSUE TITLE
Задание 2 

### ISSUE THREAD

**Issue by djadjka** [CameronCobb/training-practice#3]
а мы работаем с пул реквестами 
и тз неполное 
и гостя нет

**Comment by CameronCobb** [comment]
"а мы работаем с пул реквестами" 
м? что не так?

**Comment by CameronCobb** [comment]
Про гостя в тз ничего нет

**Comment by CameronCobb** [comment]
"Показать еще" и фильтрацию сейчас добавлю

**Comment by djadjka** [comment]
![image](https://user-images.githubusercontent.com/12067451/36389334-cf5f011c-15af-11e8-95ef-e0c681bd4734.png)

**Comment by CameronCobb** [comment]
мне вот просто интересно, где это? :D
![image](https://user-images.githubusercontent.com/25779070/36389611-b0dd52ce-15b0-11e8-85db-7c595b6f26a1.png)

**Comment by djadjka** [comment]
https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxmYW1jc2JzdXxneDozNWFmMmIxMWVjM2QwMGYw


вот тз, мб тебе про него не сказали

**Comment by CameronCobb** [comment]
Балин, судя по этому тз мне надо все переделывать, тип я форму реги не так делал и тд
Я могу это уже не переделывать? И что не так с гостем? Есть скрин, где мол не авторизованный юзер и у него две кнопочки в хедере : log in & register
И что там с пул реквестами, я не понял замечания

**Comment by djadjka** [comment]
ну тип сорян, 2 пары подряд я его показывал
если тебя на них не было, будут справки, будем говорить

**Comment by djadjka** [comment]
1) нет гостя 
2) фильтра некорректны
3) хештегов нет 
4) мобильный дизайн 
5) а как это работает ?
![image](https://user-images.githubusercontent.com/12067451/36398092-756cc0fa-15d6-11e8-9082-20bcdc79de2a.png)
6) нет визуальных сообщений
